// Development-only: replay trusted migrations in a NEW synthetic database.
// Never import this module into the native runtime or pass it a source connection.
import { DatabaseSync } from "node:sqlite";
import { workspaceMigrationPlan } from "../../../src/nativeWorkspaceBinding";
import { serializeMigrationPlan } from "../../../src/upgradeCoordinator";
export interface GeneratedSchemaObject {
    type: string;
    name: string;
    tbl_name: string;
    sql: string | null;
}
export function generateNativeWorkspaceSchemaManifest() {
    const plan = workspaceMigrationPlan();
    const serializedPlan = serializeMigrationPlan(plan);
    const db = new DatabaseSync(":memory:");
    try {
        db.exec("PRAGMA foreign_keys=ON; BEGIN;");
        for (const migration of plan) {
            for (const statement of migration.statements)
                db.exec(statement);
            db.prepare("INSERT INTO main.schema_migrations(id,name) VALUES(?,?);").run(migration.id, migration.name);
            db.exec(`PRAGMA main.user_version=${migration.id};`);
        }
        // Data admission installs dynamic legacy guards; their exact verification is
        // owned by the binding/fence verifier, not this mandatory DDL manifest.
        const objects = db.prepare("SELECT type,name,tbl_name,sql FROM main.sqlite_schema ORDER BY name COLLATE BINARY,type COLLATE BINARY;")
            .all() as unknown as GeneratedSchemaObject[];
        const engine = db.prepare("SELECT sqlite_version() AS version;").get() as {
            version: string;
        };
        return { format: "cplayout-native-schema-manifest-v1" as const, sqliteVersion: engine.version,
            targetVersion: plan.length, serializedPlan, objects };
    }
    finally {
        db.close();
    }
}
export function renderNativeWorkspaceSchemaManifest(): string {
    const manifest = generateNativeWorkspaceSchemaManifest();
    return "// Generated by generateSchemaManifest.ts from trusted migrations; do not hand-edit.\n" +
        "// SQL is SQLite's stored normalization, including ALTER TABLE rewrites and implicit indexes.\n" +
        "export const NATIVE_WORKSPACE_SCHEMA_MANIFEST = Object.freeze({\n" +
        `  format: ${JSON.stringify(manifest.format)},\n` +
        `  sqliteVersion: ${JSON.stringify(manifest.sqliteVersion)},\n` +
        `  targetVersion: ${manifest.targetVersion},\n` +
        `  serializedPlan: ${JSON.stringify(manifest.serializedPlan)},\n` +
        "  objects: Object.freeze([\n" + manifest.objects.map(row => `    Object.freeze(${JSON.stringify(row)}),`).join("\n") +
        "\n  ]),\n});\n";
}
